### ISSUE TITLE
Showing previous value

### ISSUE THREAD

**Issue by maartenvandillen** [flyskywhy/react-native-custom-picker#1]
Hi thanks for your work. When migrating to the latest RN version I had to upgrade this component as well. It is still functioning as it should but it is showing the previously selected value. Do you have the same problem? Maybe this is caused by the deprecated componentWillReceiveProps function?

**Comment by flyskywhy** [comment]
Sorry for the late of reply because github not notiied me with this issue.

I think maybe you miss used the `@flyskywhy/react-native-custom-picker`? Because the example "GIF of Font Picker to fillText" in  <https://github.com/flyskywhy/GCanvasRNExamples> which use somehow newer RN version works well, and it's code use `react-native-font-picker` which is a wrap of `@flyskywhy/react-native-custom-picker`. And there is no `componentWillReceiveProps` in `@flyskywhy/react-native-custom-picker`.

You can also use [react-native-easy-custom-picker](https://github.com/flyskywhy/react-native-easy-custom-picker) which is a wrap of `@flyskywhy/react-native-custom-picker`.

**Comment by maartenvandillen** [comment]
Sorry I can't remember exactly what this was about, but I see that I resorted to fork https://github.com/androidsolutions2/react-native-custom-picker which is working ok.
